### ISSUE TITLE
No reflections in the distance

### ISSUE THREAD

**Issue by Nord1cWarr1or** [ollerjoaco/MH_TrinityRender#12]
At medium to long range, the water just looks like a gray texture

![20230505200833_1](https://user-images.githubusercontent.com/47604048/236544055-9ce3c712-70c7-4566-b719-10631023d8ff.jpg)

![20230505201400_1](https://user-images.githubusercontent.com/47604048/236544065-afd22916-4032-4578-b91e-d755e56cb260.jpg)

![20230505151050_1](https://user-images.githubusercontent.com/47604048/236544167-ee888813-aefa-4b41-b9e7-28819186f4d9.jpg)

![20230505145440_1](https://user-images.githubusercontent.com/47604048/236545227-3740d709-090a-4035-8291-7f65950ac12b.jpg)

**Comment by ollerjoaco** [comment]
This is because of bad config in water_Default script which sets a water fog end and start distance, for fixing this by default water fog will be set to 0 and anyone wanting water fog in their maps can add a water_mapname.txt file with its own configuration for adding inmersion. Next release of Trinity will have this fixed.
